# Generated by Django 5.1.4 on 2025-01-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevTool',
            new_name='DevTools',
        ),
    ]
