# Generated by Django 5.1.4 on 2025-01-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=5)),
                ('genre', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=4)),
                ('time', models.CharField(max_length=4)),
                ('review', models.TextField()),
                ('director', models.CharField(max_length=20)),
                ('actor', models.CharField(max_length=20)),
            ],
        ),
    ]
