# Generated by Django 5.1.4 on 2025-01-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviews_genre_alter_reviews_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='time',
            field=models.IntegerField(),
        ),
    ]
