# Generated by Django 5.1.5 on 2025-01-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
