# Generated by Django 5.1.4 on 2025-01-14 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devtools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='idea_images/')),
                ('content', models.TextField()),
                ('interest', models.IntegerField(default=0)),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='devtools.devtool')),
            ],
        ),
    ]
