# Generated by Django 5.1.4 on 2025-01-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='devtool',
            field=models.TextField(),
        ),
    ]
