# Generated by Django 5.1.4 on 2025-01-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_ideas_created_at_ideas_genre_choices_ideastar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
