# Generated by Django 5.1.4 on 2025-01-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_ideas_is_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='is_starred',
        ),
    ]
